#ifndef IRESOURCESERVER_GLOBAL_H
#define IRESOURCESERVER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(IRESOURCESERVER_LIBRARY)
#  define IRESOURCESERVER_EXPORT Q_DECL_EXPORT
#else
#  define IRESOURCESERVER_EXPORT Q_DECL_IMPORT
#endif

#endif // IRESOURCESERVER_GLOBAL_H
